df1_path: "./dataset/raw/nist/donut-tt-gpt_ver1.csv"
df2_path: "./dataset/raw/nist/aws_cleaned.csv"
ground_truth_dataset_path: "./dataset/training/nist_form"
fm_model_name: "google/flan-t5-base"
trained_mode_path: "./result/t5-peft-1696754899"
gt_keys_path: "./dataset/raw/nist/keys"
result_file_name: "result_donut_tt"
split_name: "test"