
df1_path: "./dataset/raw/nist/azure_cleaned.csv"
df2_path: "./dataset/raw/nist/aws_cleaned.csv"
dataset_name_or_path: "./dataset/training/nist_form"
model_name: "google/flan-t5-base"
r_rank: 256
lora_alpha: 256
num_train_epochs: 3

result_path: "./result"
pretrained_model_name_or_path: "naver-clova-ix/donut-base"
dataset_name_or_paths: ["dataset/training/nist_form/"]
sort_json_key: False
train_batch_sizes: [2]
val_batch_sizes: [2]
input_size: [1280, 960]
max_length: 768
align_long_axis: False
num_nodes: 1
seed: 2022
lr: 3e-5
warmup_steps: 300
num_training_samples_per_epoch: 800
max_epochs: 4
max_steps: 4000
num_workers: 8
val_check_interval: 1.0
check_val_every_n_epoch: 3
gradient_clip_val: 1.0
verbose: True